### ISSUE TITLE
User can search their entries

### ISSUE THREAD

**Issue by fredrickrana** [fredrickrana/code-journal#9]
## 💰 Motivation

Coders will want to search through their entries and open one that they want to review.

## 📐 Plan

Create a responsive search bar that displays output of journal entry titles, which can be clicked in order to access that specific journal entry. 

## ✅ Task List

- [ ] Create an input element representing the search bar within the header element.
- [ ] Create the HTML and CSS for search cards and use 'display: none' to hide cards.
- [ ] Give the input element an attribute of an id = 'search-bar' and type = 'search'
- [ ] Add an addEventListener method to the search bar with the event 'keyup'
- [ ] Concert all input through the 'keyup' listener into lowercase characters, using the toLowerCase() method, in order to avoid case sensitivity while searching 
- [ ] Ensure that the search bar and results looks nice on both mobile-sized and desktop-sized screens.
- [ ] Create a function that loops through the data.entries and utilizes the includes method, which would display the search cards if the character exists in data.title.
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.

References:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search

https://www.geeksforgeeks.org/search-bar-using-html-css-and-javascript/
